<?php
/*
 *  @Package devsunsettheme
 *  --- Page template - default post type
 * - This page can detect the functions defined in /inc
 * (perhaps PHP storm can detect this page is already included in the index.php
 * (or related PHP page template)).
* */
$isRevealedPost = get_query_var('isRevealedPost');
?>

<article id="post-<?php echo get_the_ID(); ?>" <?php post_class(); ?>>
  <header class="entry-header text-center">
    <?php
    the_title('<h2 class="entry-title">','</h2>');
    ?>

  </header>

  <div class="entry-content">

    <?php the_content(); ?>
    <!-- The social media share is append after the_content generated by page builder. -->

  </div> <!--.entry-content-->

  <footer class="entry-footer">
    <?php //echo devsunset_posted_footer(); ?>

  </footer>
</article>


